name: redis_playground

services:
  redis:
    image: redis:alpine
    working_dir: /data
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: sleep infinity

  nodejs:
    image: node:22
    working_dir: /app
    volumes:
      - ./app:/app
    command: sleep infinity
